data:
  batch_size: 16
  dataset_dir: '../data/MILAN'
  dataset_name: 'MILAN'
  freq: 'S'
  split_ratio: [0.7, 0.1, 0.2]
  num_workers: 0

model:
  in_lens: 432
  label_lens: 48
  out_lens: 144 # [96, 192, 336, 720]M2M  [24, 48, 96, 192, 336, 720]S2S
  num_heads: 16
  num_hidden: 128
  num_hidden_key_per_head: None
  num_hidden_value_per_head: None
  num_hidden_ff: 256
  num_layers: 3
  drop_rate: 0.2
  attn_drop_rate: 0.0
  fc_drop_rate: 0.2
  flatten_drop_rate: 0
  res_attn_scores: True
  patch_lens: 16
  stride: 8
  padding_patch: 'end'
  if_revin: True
  if_decomp: False
  embed_type: 'timeF' # choosen from [timeF, fixed, learned]
  if_denoise: False   
  svd_cut: 31        


train:
  itr: 1 # experiment time
  model_name: 'DP-LET'
  lr: 0.0001
  adjust_lr: 'type3'
  pct_start: 0.2
  epochs: 100
  patience: 20
  model_id: 'Internet_432_144'
  model: 'DP-LET'
  checkpoints: './checkpoints/DP-LET/'
  do_predict: False
  use_multi_gpu: False
  test_flop: False

test:
  predict_lens: [1, 3, 6, 12]
  test_flop: False
  save_epoch: 43

is_training: True